global using Xunit;
global using System.Collections.Generic;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using ShoppingListApp.Models;
global using ShoppingListApp.Api.DatabaseAccess;
global using ShoppingListApp.Api.Controllers;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;